# Open and read the HTML file.
with open('updated.txt', 'rb') as file:
    html_content = file.read().decode(errors='replace')

# List of placeholders
placeholders    = [
'[linklink]',
'[benefit-title]',
'[introductory-hook]',
'[author-description]',
'[my-authors-opinion]',
'[product-target-audience]',
'[target-audience1]',
'[target-audience2]',
'[target-audience3]',
'[target-audience4]',
'[target-audience5]',
'[personal-results-description]',
'[product-benefit1]',
'[product-name]',
'[product-method-benefit]',
'[product-method-description]',
'[product-beneficiary-description]',
'[example-company1]',
'[example-company2]',
'[example-company3]',
'[example-company4]',
'[transition-to-key-points]',
'[key-point1]',
'[key-point2]',
'[benefit-examples-title]',
'[benefit-example1]',
'[benefit-example2]',
'[benefit-example3]',
'[benefit-example4]',
'[benefit-example5]',
'[conclusion-formula]',
'[transition-to-stats]',
'[statistic1]',
'[transition-to-steps]',
'[transition-to-benefits]',
'[benefit-point1]',
'[benefit-explanation1]',
'[benefit-usecase1]',
'[transition-to-benefit2]',
'[benefit-point2]',
'[benefit-explanation2]',
'[benefit-usecase2]',
'[step1-title]',
'[step1-description1]',
'[step1-description2]',
'[step1-description3]',
'[transition-to-step1-topics]',
'[step1-topic1]',
'[step1-topic2]',
'[step1-topic3]',
'[step1-topic4]',
'[step1-topic5]',
'[step2-title]',
'[step2-description1]',
'[step2-description2]',
'[step2-description3]',
'[step3-title]',
'[step3-description1]',
'[step3-description2]',
'[transition-to-step3-topics]',
'[step3-topic1]',
'[step3-topic2]',
'[step3-topic3]',
'[step3-topic4]',
'[step3-topic5]',
'[step3-conclusion1]',
'[step3-conclusion2]',
'[step3-elaboration1]',
'[step3-elaboration2]',
'[step4-title]',
'[transition-to-step4]',
'[transition-to-step4-explanation]',
'[step4-explanation-conclusion]',
'[step4-topic1]',
'[step4-topic2]',
'[step4-topic3]',
'[step4-topic4]',
'[step4-topic5]',
'[4-steps-conclusion]',
'[putting-it-all-together-title]',
'[transition-to-system-benefits]',
'[system-benefit1]',
'[system-benefit2]',
'[system-benefit3]',
'[system-benefit4]',
'[system-benefit5]',
'[product-name-title]',
'[transition-to-ethics]',
'[unethical-point1]',
'[unethical-elaboration1]',
'[unethical-point2]',
'[unethical-elaboration2]',
'[transition-to-ethical]',
'[ethical-point1]',
'[ethical-elaboration1]',
'[ethical-point2]',
'[ethical-elaboration2]',
'[how-to-start-title]',
'[how-to-start-paragraph1]',
'[how-to-start-paragraph2]',
'[transition-to-bonus]',
'[bonus-offer1]',
'[bonus-offer2]',
'[bonus-offer3]',
'[bonus-offer4]',
'[proof-section-title]',
'[bonus-section]',
'[bonus-option1]',
'[bonus-option2]',
'[bonus-option3]',
'[recommendation-paragraph]',
'[special-bonus]',
'[bonus-join-now-sentence]',
'[bonus-join-now-paragraph1]',
'[bonus-join-now-paragraph2]',
'[bonus-join-now-paragraph3-action-text]',
'[review-section-title]',
'[comment5]',
'[response5]',
'[comment4]',
'[response4]',
'[comment3]',
'[response3]',
'[comment2]',
'[response2]',
'[comment1]',
'[response1]',
'[benefit-title]'	,
'[introductory-hook]',
'[benefit-point1]', 
'[benefit-point2]'	,
'[statistic1]'	,
'[product-name]'	,
'[product-method-description]'	,
'[product-name-title]'	,
]

# List of replacements
replacements = [
    'linklink',


 "Unlock Your Potential: Revolutionary Life Improvement Course!"	,
"Imagine waking up every day, feeling energized and knowing that you're living your life to its fullest potential. That's exactly what this course promises to deliver!"	,
"Hi, I'm Gary Halbert, a seasoned copywriter and your guide on this transformative journey."	,
"I believe this course is a game-changer. Its unique approach has not only transformed my life but has also enabled countless others to live their dream lives."	,
"This course is designed for anyone seeking to enhance their life, whether you're stuck in a rut, seeking personal growth, or merely looking for new ways to challenge yourself."	,
"Individuals feeling stuck and seeking change."	,
"Those looking to improve personal or professional relationships."	,
"People seeking clarity and purpose in their lives."	,
"Professionals looking for personal development and improved productivity."	,
"Anyone interested in personal growth and development."	,
"After completing this course, I've found renewed energy, clarity, and purpose in my life. I feel more confident and empowered to take on new challenges."	,
"Gain powerful insights into your behaviors and patterns, empowering you to live your best life."	,
"The Life Unlocker Course"	,
"This course uses scientifically-backed methods to help you understand and reframe your mindset."	,
"The Life Unlocker Course guides you through personal reflection activities, video lessons, and real-life applications. It equips you with tools to improve self-awareness and mindset."	,
"The benefits of this course extend beyond the individual, impacting personal and professional relationships and creating a ripple effect of positive change."	,
"Apple Inc."	,
"Tesla"	,
"Microsoft"	,
"Amazon"	,
"Let's delve into the key points that make this course a life-altering experience."	,
"Designed by world-leading psychologists and personal development experts."	,
"Comprehensive and step-by-step learning approach, suitable for everyone."	,
"Life-Transforming Benefits of the Course"	,
"Improved self-awareness and understanding."	,
"Effective strategies for overcoming personal barriers."	,
"Practical tools for enhancing productivity and success."	,
"Improved relationship building and communication skills."	,
"Techniques for maintaining motivation and achieving goals."	,
"In essence, The Life Unlocker Course equips you with the tools, techniques, and insights to unlock a life of purpose, success, and happiness."	,
"But don't just take my word for it. Let's look at some statistics."	,
"A whopping 97% of previous students reported significant improvement in their personal and professional lives after taking the course."	,
"Now, let's walk through the steps you will go through in the course."	,
"Before we delve into the specifics, it's crucial to understand how each step benefits you."	,
"Developing Self-Awareness"	,
"This is the first step towards any personal development. By understanding yourself better, you can recognize what you need to work on and what's holding you back."	,
"Great for people feeling stuck or who lack a clear direction in life."	,
"Once you've gained self-awareness, it's time to move onto the next step."	,
"Developing Mindset and Habits"	,
"We help you develop a growth mindset, enabling you to embrace challenges, persist in the face of setbacks, see effort as a path to mastery, and learn from criticism."	,
"Perfect for people who want to be more resilient and successful."	,
"Step 1: Understanding Yourself"	,
"In this initial phase, you'll participate in a series of self-reflection activities to dig deep into your strengths, weaknesses, and values."	,
"Through various exercises, you'll gain a clear understanding of what drives you and what may be holding you back."	,
"You'll learn how to use this newfound self-awareness to set clear and achievable personal goals."	,
"The key topics covered in this first step include:"	,
"The Importance of Self-Awareness"	,
"Identifying Your Strengths and Weaknesses"	,
"Understanding Your Values and Beliefs"	,
"Setting Personal Goals"	,
"Planning for Success"	,
"Step 2: Developing a Positive Mindset"	,
"This step focuses on building a resilient and growth-oriented mindset to help you overcome obstacles and embrace opportunities."	,
"You'll learn the power of positive thinking and how to cultivate habits that promote success and wellbeing."	,
"By the end of this step, you'll be equipped with strategies to transform negative thought patterns and maintain a positive outlook, even in challenging situations."	,
"Step 3: Harnessing the Power of Habits"	,
"Here, you'll discover the profound impact that your daily habits can have on your life, and how to harness this power to your advantage."	,
"You'll learn about habit formation and how to establish habits that align with your personal goals and values."	,
"The topics covered in this pivotal step include:"	,
"Understanding the Power of Habits"	,
"How Habits are Formed"	,
"Identifying and Changing Unhelpful Habits"	,
"Creating Positive Habits"	,
"Maintaining Your New Habits"	,
"With an understanding of habits and their power, you're well on your way to making profound changes in your life."	,
"By consciously shaping your habits, you can steer your life in the direction that aligns with your goals and values."	,
"Remember, habits don't change overnight. Be patient with yourself and celebrate the small victories along the way."	,
"Stay committed, even when it's challenging. Your future self will thank you."	,
"Step 4: Achieving Your Goals"	,
"Now that you have the right mindset and habits, it's time to focus on achieving your goals."	,
"In this final step, we will explore effective goal-setting and achievement strategies."	,
"You'll learn how to break your goals into manageable steps, overcome obstacles, and maintain motivation until your goals are achieved."	,
"Setting SMART Goals"	,
"Breaking Down Your Goals"	,
"Overcoming Obstacles"	,
"Maintaining Motivation"	,
"Celebrating Your Achievements"	,
"By following these four steps – Understanding Yourself, Developing a Positive Mindset, Harnessing the Power of Habits, and Achieving Your Goals – you're on your way to unlocking your potential and living your best life."	,
"Pulling It All Together: Your Journey to Success"	,
"The journey may seem challenging, but the benefits you will reap from this course are immense."	,
"Increased self-awareness and self-understanding"	,
"Improved ability to overcome obstacles and setbacks"	,
"Increased motivation and persistence"	,
"Improved personal and professional relationships"	,
"A clear path towards achieving your personal goals"	,
"The Life Unlocker Course: Your Guide to Personal Success"	,
"It's important to note that while personal development is a worthy goal, it should always be pursued ethically."	,
"It's unethical to use personal development techniques to manipulate others or achieve unfair advantage."	,
"Personal development should be about improving oneself, not harming or exploiting others."	,
"It's unethical to expect instant results or to pressure others into personal development."	,
"Real growth takes time, and everyone has their own pace and process. Respect your journey and those of others."	,
"So, how do we ensure that we pursue personal development ethically?"	,
"Ensure your goals align with your values and don't harm others."	,
"Seeking growth at the expense of others or compromising your values for success isn't sustainable or ethical. Prioritize win-win scenarios and maintain your integrity."	,
"Be patient and compassionate with yourself and others."	,
"Change takes time and everyone's journey is unique. Avoid comparing yourself with others and practice self-compassion."	,
"Ready to Unlock Your Potential? Here's How to Start"	,
"To begin your transformation journey, simply register for The Life Unlocker Course. It's conveniently structured into modules, allowing you to learn at your own pace, from the comfort of your home."	,
"Each step builds upon the previous one, so all you need to do is follow along and be ready to engage in deep, meaningful self-reflection and learning."	,
"But that's not all! To make your journey even more rewarding, we've included some incredible bonuses."	,
"Bonus 1: Access to our exclusive community of learners where you can connect, share experiences, and learn from others who are on the same journey."	,
"Bonus 2: A collection of motivational e-books that will keep you inspired throughout your journey."	,
"Bonus 3: An additional module on mindfulness and its benefits, helping you to live in the present and reduce stress."	,
"Bonus 4: A one-on-one coaching call with a certified life coach to provide personalized guidance on your journey."	,
"Proof that The Life Unlocker Course Works"	,
"Bonuses to Boost Your Journey"	,
"Exclusive Learner's Community Access"	,
"Motivational E-Books Collection"	,
"Mindfulness Module"	,
"Don't just take my word for it. Numerous students have used The Life Unlocker Course to transform their lives. It's now your turn to take this transformational journey."	,
"Special Bonus: A Personalized Coaching Call"	,
"Join The Life Unlocker Course now and start your journey towards a fulfilled and empowered life!"	,
"The time for change is now. If you're ready to invest in your future and unlock your potential, don't wait. Sign up for The Life Unlocker Course today!"	,
"Remember, you're not just getting a course. You're gaining a community, resources, and a guided journey to becoming the best version of yourself."	,
"Sign up today and take the first step towards your transformed life. You have the power to change. Unlock it with The Life Unlocker Course."	,
"Here's What Others Are Saying About The Life Unlocker Course"	,
"I was skeptical at first, but this course has completely changed my life. I've gained so much self-awareness and have finally been able to overcome barriers that were holding me back."	,
"We're so glad to hear that you've seen significant growth through our course. Your journey is just beginning!"	,
"The support I've received from the community has been invaluable. I don't feel alone on this journey, and that's made a huge difference."	,
"Our community is indeed a valuable aspect of the course. It's great to hear you're benefiting from it!"	,
"The resources provided, particularly the motivational e-books, keep me inspired and motivated. Thanks for this life-changing course!"	,
"We're thrilled to hear that the resources have been helpful. Keep that motivation going!"	,
"The one-on-one coaching call was a game-changer for me. It helped me to personalize the course to my specific needs and circumstances."	,
"We're delighted to know the coaching call was beneficial for you. Personalized guidance can make all the difference!"	,
"I've taken other personal development courses, but none were as comprehensive and practical as this one. The Life Unlocker Course is truly a game-changer!"	,
"Your positive feedback means a lot to us. We're proud to provide a practical, comprehensive course to help individuals unlock their potential!"	,"Discover the Benefits of the Air Fountain System"	,
"Are you tired of relying on expensive bottled water or facing water scarcity? Introducing the Air Fountain System, the revolutionary solution that allows you to generate your own clean drinking water at home!"	,
"Save Money: Eliminate the need to purchase bottled water and reduce your expenses on water bills."	,
"Sustainable Water Source: Gain access to a reliable and sustainable source of clean water, even in drought-prone areas or during emergencies."	,
"According to a study conducted by XYZ Research, the Air Fountain System has helped users save up to 50% on their monthly water expenses."	,
"Air Fountain System"	,
"The Air Fountain System utilizes the principle of water condensation to extract moisture from the air, collecting it as fresh, drinkable water in a storage container. With simple assembly and easy-to-follow instructions, you can set up the system and start generating clean water in no time."	,
"Learn About the Air Fountain System"	,


    
    
    ]

# Check if both lists have same length
if len(placeholders) != len(replacements):
    print(len(placeholders))
    print(len(replacements))

    raise ValueError("Both lists should have same number of elements")

# Replace placeholders with replacements
for i in range(len(placeholders)):
    if(placeholders[i] in html_content ):
        html_content = html_content.replace(placeholders[i], replacements[i])

# Write the new HTML to a file.
with open('updated.html', 'wb') as file:
    file.write(html_content.encode())
 


with open('top-recomendations updated.txt', 'rb') as file:
    html_content = file.read().decode(errors='replace')

# Replace placeholders with replacements
for i in range(len(placeholders)):
    if(placeholders[i] in html_content ):
        html_content = html_content.replace(placeholders[i], replacements[i])


# Write the new HTML to a file.
with open('article.html', 'wb') as file:
    file.write(html_content.encode())
