# Open and read the HTML file.
with open('updated.txt', 'rb') as file:
    html_content = file.read().decode(errors='replace')

# List of placeholders
placeholders    = [
'[linklink]',
'[benefit-title]',
'[introductory-hook]',
'[author-description]',
'[my-authors-opinion]',
'[product-target-audience]',
'[target-audience1]',
'[target-audience2]',
'[target-audience3]',
'[target-audience4]',
'[target-audience5]',
'[personal-results-description]',
'[product-benefit1]',
'[product-name]',
'[product-method-benefit]',
'[product-method-description]',
'[product-beneficiary-description]',
'[example-company1]',
'[example-company2]',
'[example-company3]',
'[example-company4]',
'[transition-to-key-points]',
'[key-point1]',
'[key-point2]',
'[benefit-examples-title]',
'[benefit-example1]',
'[benefit-example2]',
'[benefit-example3]',
'[benefit-example4]',
'[benefit-example5]',
'[conclusion-formula]',
'[transition-to-stats]',
'[statistic1]',
'[transition-to-steps]',
'[transition-to-benefits]',
'[benefit-point1]',
'[benefit-explanation1]',
'[benefit-usecase1]',
'[transition-to-benefit2]',
'[benefit-point2]',
'[benefit-explanation2]',
'[benefit-usecase2]',
'[step1-title]',
'[step1-description1]',
'[step1-description2]',
'[step1-description3]',
'[transition-to-step1-topics]',
'[step1-topic1]',
'[step1-topic2]',
'[step1-topic3]',
'[step1-topic4]',
'[step1-topic5]',
'[step2-title]',
'[step2-description1]',
'[step2-description2]',
'[step2-description3]',
'[step3-title]',
'[step3-description1]',
'[step3-description2]',
'[transition-to-step3-topics]',
'[step3-topic1]',
'[step3-topic2]',
'[step3-topic3]',
'[step3-topic4]',
'[step3-topic5]',
'[step3-conclusion1]',
'[step3-conclusion2]',
'[step3-elaboration1]',
'[step3-elaboration2]',
'[step4-title]',
'[transition-to-step4]',
'[transition-to-step4-explanation]',
'[step4-explanation-conclusion]',
'[step4-topic1]',
'[step4-topic2]',
'[step4-topic3]',
'[step4-topic4]',
'[step4-topic5]',
'[4-steps-conclusion]',
'[putting-it-all-together-title]',
'[transition-to-system-benefits]',
'[system-benefit1]',
'[system-benefit2]',
'[system-benefit3]',
'[system-benefit4]',
'[system-benefit5]',
'[product-name-title]',
'[transition-to-ethics]',
'[unethical-point1]',
'[unethical-elaboration1]',
'[unethical-point2]',
'[unethical-elaboration2]',
'[transition-to-ethical]',
'[ethical-point1]',
'[ethical-elaboration1]',
'[ethical-point2]',
'[ethical-elaboration2]',
'[how-to-start-title]',
'[how-to-start-paragraph1]',
'[how-to-start-paragraph2]',
'[transition-to-bonus]',
'[bonus-offer1]',
'[bonus-offer2]',
'[bonus-offer3]',
'[bonus-offer4]',
'[proof-section-title]',
'[bonus-section]',
'[bonus-option1]',
'[bonus-option2]',
'[bonus-option3]',
'[recommendation-paragraph]',
'[special-bonus]',
'[bonus-join-now-sentence]',
'[bonus-join-now-paragraph1]',
'[bonus-join-now-paragraph2]',
'[bonus-join-now-paragraph3-action-text]',
'[review-section-title]',
'[comment5]',
'[response5]',
'[comment4]',
'[response4]',
'[comment3]',
'[response3]',
'[comment2]',
'[response2]',
'[comment1]',
'[response1]',
'[benefit-title]'	,
'[introductory-hook]',
'[benefit-point1]', 
'[benefit-point2]'	,
'[statistic1]'	,
'[product-name]'	,
'[product-method-description]'	,
'[product-name-title]'	,
'[img-alt-1]'	,
'[img-alt-2]'	,
'[img-alt-3]'	,
'[img-alt-4]'	,
'[img-alt-5]'	
]

# List of replacements
replacements = [
    'https://e6d24pnxocj7cyb9v2zhl4zp8z.hop.clickbank.net/?tid=endopeak',

"EndoPeak: Unleash Your Sexual Potential - A Review",
"Discover EndoPeak - the ultimate solution for enhancing your sexual performance and reigniting passion in your love life. Join me for an in-depth review of this natural male enhancement formula that delivers impressive results.",
"Hey there, fellow health enthusiast! Let's dive right into the world of men's health and check out if EndoPeak is the real deal or just another bedroom revolution wannabe.",
"EndoPeak: A remarkable male enhancement solution with impressive benefits. Extensive research reveals compelling evidence of its effectiveness and positive impact on sexual health.",
"EndoPeak: Natural solution for men's sexual performance. Enhance satisfaction organically, no synthetics.",
"30-something men seeking to preserve their youthful energy and vigor.",
"Struggling with getting and keeping it up? Middle-aged men, listen up!",
"Stressed pros seeking stamina and enhanced performance.",
"Guys looking for a safe and lasting way to enhance themselves without the risks of drugs.",
"Men craving to reignite passion and bliss in their love lives.",
"Testimonials reveal EndoPeak's transformative results. Let's explore the potential benefits of this male enhancement formula.",
"EndoPeak: better circulation, higher libido, stress protection, improved blood flow, testosterone support, enhanced performance, more stamina, healthy T levels.",
"EndoPeak",
"Unleash Your Sexual Performance Potential",
"EndoPeak's formula boosts your erection quality and duration. With selected natural ingredients, it amps up blood flow, stamina, and libido. Get ready for revitalized sexual experiences.",
"EndoPeak: The ultimate solution for men craving a mind-blowing sex life. Take charge, unleash pleasure, and forge stronger bonds with your partner.",
"Mark B. - New York, USA",
"Thomas J. - Arizona, USA",
"Chad B. - Texas, USA",
"Sarah L. - California, USA",
"Now, let's dive into the key points that reveal EndoPeak's effectiveness and potential advantages.",
"Introducing EndoPeak's formula - 8 carefully chosen ingredients: Hawthorn Berry, Tribulus, Chrysin, Epimedium, Saw Palmetto, Tongkat Ali, Winged Treebine, and Magnesium.",
"Real testimonials. Life-changing results. EndoPeak delivers.",
"EndoPeak: Real-Life Success Stories",
"Mark B. from NY thought his prime was over, but with EndoPeak, he and his partner relive their youthful love life.",
"Meet Thomas J. from Arizona. He used to have trouble relaxing before getting intimate. But ever since he started using EndoPeak, things have changed. Now, he's getting rock-solid erections and keeping up with his young wife without breaking a sweat.",
"Texas man Chad B. conquered performance anxiety, gaining stamina, reliable erections, and unwavering confidence with EndoPeak. Love life transformed forever.",
"Sarah L. from California saw her husband's ED battles, but with EndoPeak, their intimacy soared and their bond grew stronger.",
"EndoPeak users experience life-changing results. Astounding potential for personal satisfaction and enhanced relationships.",
"EndoPeak: Unleash your sexual potential. Natural. Powerful. Elevate your intimate experiences.",
"Check out these powerful stats that reveal the true power of EndoPeak.",
"New study: Vascular endothelium key for treating erectile dysfunction. Circulation crucial for strong erections.",
"Discover the steps for a satisfying sex life with EndoPeak.",
"Follow these steps for enhanced sexual performance and satisfaction.",
"Get rock-hard boners and mind-blowing climaxes.",
"EndoPeak: Boosts blood flow, improves circulation, and delivers rock-solid erections for mind-blowing pleasure in the bedroom.",
"Picture the joy and assurance of always performing at your best, bringing pleasure and excitement to both you and your partner.",
"But wait, there's more! Now, let's explore another amazing advantage of EndoPeak.",
"Boost Your Stamina for Longer-lasting Pleasure",
"EndoPeak's blend amps up stamina, for longer pleasure and ultimate partner satisfaction. No more limits, just pure joy in extended intimacy.",
"Picture the joy of satisfying your partner's desires, creating unforgettable experiences, and strengthening your relationship.",
"Step 1: Take the EndoPeak dosage as recommended.",
"Take one EndoPeak capsule daily with water for remarkable benefits.",
"Be consistent. Use EndoPeak daily, same time.",
"Follow this simple step and watch your sexual experiences transform.",
"Let's dive into Step 1 essentials.",
"EndoPeak Dosage: Mastering the recommended dose.",
"EndoPeak: Optimize your schedule for maximum results.",
"Side Effects: Let's talk about your concerns.",
"Safely use EndoPeak for the long haul: Long-term benefits explained.",
"Consultation: The when and why of seeking professional advice.",
"Get healthy. Step 2.",
"To get the most out of EndoPeak, a healthy lifestyle is a must.",
"Exercise, diet, and stress control boost sexual health.",
"Boost your sex life with EndoPeak by embracing positive lifestyle changes.",
"Step 3: Open Communication",
"Communication is key for relationships, especially when it comes to intimacy.",
"Open, truthful communication builds trust and closeness in your relationship, enabling you and your partner to uncover desires and guarantee a satisfying experience.",
"Step 3: Open Communication - let's dive in.",
"Powerful Communication: Express desires, listen to partner's needs.",
"Safe Space: Make sure both partners can freely express desires and concerns.",
"Unleashing Desires: Enhancing intimacy and understanding through open conversations about fantasies.",
"Active Listening: Uncover your partner's needs and desires like a pro.",
"Sexual Concerns: How to address and resolve any issues that come up.",
"Open communication fosters intimacy, strengthens connection, and enhances sexual satisfaction for both partners.",
"Honesty is key for a strong and passionate relationship.",
"To have a fulfilling and intimate connection, openly express desires, actively listen to your partner, and create a safe space for open dialogue. When both partners feel heard, understood, and respected, trust and satisfaction in the relationship soar.",
"Embrace your fantasies and desires. Talk about them openly. It leads to new adventures and stronger connections. Address concerns, find solutions, and grow closer.",
"Step 4: The Power of Intimate Bonding Unleashed.",
"Time for the last step in our quest for a better sex life.",
"Step 4: Deepen the connection. Enhance your sexual experiences.",
"Build emotional connection for mind-blowing satisfaction in bed.",
"Emotional Intimacy: Building a powerful bond with your partner.",
"Unleash Pleasure: Elevate sensations with touch, sight, taste, and smell.",
"Memorable moments: Strengthen your bond through shared experiences.",
"Spice up your relationship with spontaneity and variety: Discover new activities and experiences for added excitement.",
"Trust & Respect: Building a bond of trust and respect in your relationship.",
"Improve your sex life now. Boost your sexual health, communicate openly, build emotional intimacy, and strengthen your bond. Take action today for a more satisfying and fulfilling sex life.",
"The EndoPeak System: Maximum Benefits, Minimum Effort.",
"Now, let's talk about how the EndoPeak system combines these steps for incredible benefits to your sexual well-being.",
"Supercharge your sex life with EndoPeak! Our all-natural formula and proven steps will boost stamina, give you rock-hard erections, and intensify pleasure.",
"Discover the EndoPeak system: Open communication, emotional bonding, and mutual exploration lead to deeper intimacy and connection for couples. Experience a more fulfilling and satisfying sex life.",
"EndoPeak boosts confidence and self-esteem, improving your sexual relationship and outlook on life.",
"EndoPeak: Immediate and long-lasting sexual health. Healthy choices, communication, and bonding for ongoing satisfaction.",
"Boost Your Relationship: The EndoPeak system amps up your sex life and takes your relationship to new heights. It fosters intimacy and puts your desires front and center, resulting in a more blissful and satisfying partnership.",
"Unlock Your Sexual Potential with EndoPeak!",
"Now, let's talk ethics before we wrap up.",
"Truthful claims: Making sure product claims match real results.",
"Companies must provide accurate info about their products, avoiding exaggerated promises. Transparency and honesty build trust with consumers, aiding informed decisions.",
"Protecting Privacy: Safeguarding personal info and following privacy rules.",
"Privacy matters. Responsible companies prioritize it. They handle personal information with care. Respecting privacy shows ethics. It makes customers feel safe and secure.",
"Now, let's talk about the ethical practices of the EndoPeak system.",
"Proven Science: Creating products rooted in solid research and scientific evidence.",
"EndoPeak's formula is backed by science and includes proven ingredients. Our dedication to scientific integrity shows our ethical product development.",
"Safe and reliable production processes: Quality manufacturing standards.",
"EndoPeak: FDA registered, GMP certified. Quality control ensures highest standards for safety and reliability. Trustworthy solution.",
"EndoPeak: Unleash Your Sexual Potential - Here's How!",
"Want the life-changing power of EndoPeak? Here's a quick guide to kickstart your journey to sexual bliss.",
"Unlock your sexual potential with EndoPeak. Follow these steps:",
"Wait! There's more! Exclusive bonus offer for you.",
"Order EndoPeak now and get a free 'The Art of Sensual Massage' e-book to take your intimate moments to the next level.",
"Get the 'Guide to Aphrodisiac Foods' e-book. It's loaded with tasty recipes and info on natural foods that amp up your libido and improve your sex life.",
"But wait, there's more! Gain access to our exclusive online community. Connect with like-minded individuals, share experiences, and receive ongoing support on your journey to sexual enhancement.",
"Get ready for mind-blowing pleasure and a whole new level of sexual well-being with our epic bonus package. Elevate your experience with EndoPeak!",
"EndoPeak: Real Results Proven!",
"See what thrilled customers say about EndoPeak and how it transformed their lives.",
"Jane R. from Ohio, USA says: 'EndoPeak has transformed our intimacy. With enhanced stamina and performance, it's taken our moments to new heights. It's reignited the passion in our relationship.'",
"David T. from London, UK says: 'EndoPeak gave me a big boost in sexual confidence and performance. It improved my stamina and made intimate moments more satisfying. Highly recommended for anyone wanting to enhance their sex life.'",
"EndoPeak rocks! Amy S. from Sydney, Australia is blown away. It's not just about mind-blowing sex, but also the deep connection and intimacy it brings. Amy feels alive and fulfilled, and her partner is over the moon. EndoPeak, you've reignited their spark! Thank you!",
"For a better sex life, stronger connection, and overall relationship satisfaction, choose EndoPeak. With its proven formula and recommended steps, it's the ultimate solution. Order now and take the first step towards a more fulfilling sex life.",
"Limited-time offer: Get 20% off your first purchase of EndoPeak. Unlock your sexual potential at a more affordable price. Act now and experience the transformation.",
"Join satisfied customers, experience EndoPeak's benefits. Order now, enhance sexual satisfaction.",
"Claim your discount and get exclusive bonuses by visiting our official website. Choose your preferred package, follow the simple ordering process, and instantly access your bonuses after purchase.",
"Limited time offer! Don't wait. Transform your sex life now with EndoPeak - the key to unlocking your sexual potential.",
"Buy Now",
"EndoPeak: Customer Reviews That Matter!",
"John D. from California says: 'EndoPeak is the real deal for male enhancement. The results are mind-blowing, making my partner ecstatic. It's boosted my confidence and stamina, leaving her fully satisfied. I highly recommend EndoPeak for a better sex life.'",
"John, thanks for sharing your awesome experience with EndoPeak. It's great to hear how it's taken your sexual performance to new heights. We appreciate your recommendation and hope you keep enjoying those intimate moments.",
"Sarah W. from Texas says EndoPeak transformed her love life. No more worries about performance or feeling inadequate. It gives her energy, stamina, and confidence to please her partner like never before. EndoPeak is a game-changer!",
"Sarah, your transformation with EndoPeak is incredible. It has empowered you to conquer performance concerns and reignite passion in your relationship. Your satisfaction is our ultimate goal, and we're thrilled to be a part of your journey. Thank you!",
"Michael R. from Florida, USA was skeptical, but EndoPeak surpassed expectations. Enhanced endurance and potent erections elevated his sexual experiences. Grateful for this product's positive impact on his relationship.",
"Thanks, Michael, for sharing your positive experience with EndoPeak. We get the skepticism, but we're stoked to have exceeded your expectations. It's awesome that EndoPeak has amped up your sex life and brought positivity to your relationship. We appreciate your trust in our product.",
"Linda M. from New York says, 'EndoPeak is the real deal. It's all-natural and has transformed my sex life. I feel like a whole new person!'",
"Thanks, Linda, for the positive EndoPeak experience share. Thrilled to hear our product boosted your libido and sexual satisfaction! Thanks for the kind words. We're stoked to have helped you transform. Feel the confidence, savor the pleasure!",
"Robert K. London, UK: 'EndoPeak shattered my skepticism about male enhancement products. Wow! The results are mind-blowing! It's given me the energy and zest to fully savor my intimate moments. EndoPeak: A game-changer in male enhancement.",
"Thanks, Robert, for sharing your EndoPeak experience. Skepticism understood. Thrilled to exceed expectations. Great news! Our product has given you the stamina and vitality for better intimate moments. Thanks for your support. Stay satisfied.",
"Unleash Your Sexuality with EndoPeak",
"Ready to level up your sex life? Unlock your sexual potential with EndoPeak. Enhanced performance, increased stamina, deeper connection with your partner.",
"Unleash Your Stamina: EndoPeak's formula supercharges endurance, helping you reach peak performance and satisfy your partner like never before.",
"Get intense pleasure: EndoPeak delivers stronger, longer erections for heightened satisfaction and pleasure, for you and your partner.",
"9 out of 10 men who tried EndoPeak saw a major boost in their bedroom game. Get ready for a more satisfying sex life.",
"Unlock Your Sexual Power with EndoPeak",
"EndoPeak: Remarkable results with carefully selected ingredients. Get ready for a mind-blowing sex life! Our natural formula tackles all the important stuff like stamina, performance, and pleasure. It's the ultimate solution for a truly satisfying experience.",
"Unleash the EndoPeak Power for Male Enhancement",
"EndoPeak: Amp Up Stamina and Performance",
"EndoPeak: More Pleasure, More Satisfaction",
"Unleash Your Sexuality with EndoPeak",
"Boost Performance with EndoPeak",
"Unleash Your True Sexual Potential with EndoPeak." 
    
    
    ]

# Check if both lists have same length
if len(placeholders) != len(replacements):
    print(len(placeholders))
    print(len(replacements))

    raise ValueError("Both lists should have same number of elements")

# Replace placeholders with replacements
for i in range(len(placeholders)):
    if(placeholders[i] in html_content ):
        html_content = html_content.replace(placeholders[i], replacements[i])

# Write the new HTML to a file.
with open('updated.html', 'wb') as file:
    file.write(html_content.encode())
 


with open('top-recomendations updated.txt', 'rb') as file:
    html_content = file.read().decode(errors='replace')

# Replace placeholders with replacements
for i in range(len(placeholders)):
    if(placeholders[i] in html_content ):
        html_content = html_content.replace(placeholders[i], replacements[i])


# Write the new HTML to a file.
with open('article.html', 'wb') as file:
    file.write(html_content.encode())
